In [ ]:
import pandas as pd
import seaborn as sns
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix , classification_report , accuracy_score

In [ ]:
df = sns.load_dataset('titanic')

In [ ]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [ ]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [ ]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.drop( ['deck','embark_town','who','class','adult_male', 'alive'] ,axis = 1 ,  inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  891 non-null    int64
 1   pclass    891 non-null    int64
 2   sex       891 non-null    object
 3   age       714 non-null    float64
 4   sibsp     891 non-null    int64
 5   parch     891 non-null    int64
 6   fare      891 non-null    float64
 7   embarked  889 non-null    object
 8   alone     891 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 56.7+ KB

In [ ]:
df['age'].fillna(df['age'].mean() , inplace = True)

/tmp/ipython-input-2640674786.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['age'].fillna(df['age'].mean() , inplace = True)

In [ ]:
df.dropna(subset = ['embarked'],inplace = True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  889 non-null    int64
 1   pclass    889 non-null    int64
 2   sex       889 non-null    object
 3   age       889 non-null    float64
 4   sibsp     889 non-null    int64
 5   parch     889 non-null    int64
 6   fare      889 non-null    float64
 7   embarked  889 non-null    object
 8   alone     889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [ ]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  alone
0         0       3    male  22.0      1      0   7.2500        S  False
1         1       1  female  38.0      1      0  71.2833        C  False
2         1       3  female  26.0      0      0   7.9250        S   True
3         1       1  female  35.0      1      0  53.1000        S  False
4         0       3    male  35.0      0      0   8.0500        S   True

In [ ]:
le = LabelEncoder()

In [ ]:
df['sex'] = le.fit_transform(df['sex'])

In [ ]:
df['embarked'] = le.fit_transform(df['embarked'])   # s=2 , c=0 , q=1

In [ ]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  alone
0         0       3    1  22.0      1      0   7.2500         2  False
1         1       1    0  38.0      1      0  71.2833         0  False
2         1       3    0  26.0      0      0   7.9250         2   True
3         1       1    0  35.0      1      0  53.1000         2  False
4         0       3    1  35.0      0      0   8.0500         2   True

In [ ]:
df = df.astype(int)

In [ ]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  alone
0         0       3    1   22      1      0     7         2      0
1         1       1    0   38      1      0    71         0      0
2         1       3    0   26      0      0     7         2      1
3         1       1    0   35      1      0    53         2      0
4         0       3    1   35      0      0     8         2      1

**Logistics Regression**

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
x = df.drop('survived',axis = 1)
y = df['survived']

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state = 2)

In [ ]:
model = LogisticRegression()

In [ ]:
model.fit(x_train , y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [ ]:
y_pred = model.predict(x_test)

In [ ]:
confusion_matrix(y_pred , y_test)

array([[91, 19],
       [20, 48]])

In [ ]:
print(classification_report(y_pred , y_test))

              precision    recall  f1-score   support

           0       0.82      0.83      0.82       110
           1       0.72      0.71      0.71        68

    accuracy                           0.78       178
   macro avg       0.77      0.77      0.77       178
weighted avg       0.78      0.78      0.78       178

In [ ]:
print(f'Logistic Regression: {accuracy_score(y_pred , y_test)}')

Logistic Regression: 0.7808988764044944

KNN --> K-Nearest Neighbours

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [ ]:
x_test_scaled

array([[ 0.80313075,  0.73187236, -0.0255927 , ..., -0.48298047,
        -0.61690357,  0.8227313 ],
       [ 0.80313075,  0.73187236, -0.6585113 , ..., -0.46334308,
         0.61864133,  0.8227313 ],
       [-0.38899026, -1.36635848, -0.42116683, ...,  0.6559884 ,
         0.61864133, -1.21546366],
       ...,
       [ 0.80313075,  0.73187236, -0.0255927 , ..., -0.44370568,
         0.61864133,  0.8227313 ],
       [ 0.80313075,  0.73187236,  1.39847415, ..., -0.48298047,
         0.61864133,  0.8227313 ],
       [ 0.80313075,  0.73187236, -0.26293718, ..., -0.48298047,
         0.61864133,  0.8227313 ]])

In [ ]:
knn_model = KNeighborsClassifier(n_neighbors = 5)
knn_model.fit(x_train_scaled , y_train)

KNeighborsClassifier()

In [ ]:
y_pred_knn = knn_model.predict(x_test_scaled)

In [ ]:
confusion_matrix(y_pred_knn , y_test)

array([[96, 19],
       [15, 48]])

In [ ]:
print(classification_report(y_pred_knn , y_test))

              precision    recall  f1-score   support

           0       0.86      0.83      0.85       115
           1       0.72      0.76      0.74        63

    accuracy                           0.81       178
   macro avg       0.79      0.80      0.79       178
weighted avg       0.81      0.81      0.81       178

In [ ]:
print(f'KNN accuracy: {accuracy_score(y_pred_knn , y_test)}')

KNN accuracy: 0.8089887640449438

**Naive Bayes**

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
NB_model = GaussianNB()

In [ ]:
NB_model.fit(x_train , y_train)

GaussianNB()

In [ ]:
y_pred_NB = NB_model.predict(x_test)

In [ ]:
confusion_matrix(y_pred_NB , y_test)

array([[89, 18],
       [22, 49]])

In [ ]:
print(classification_report(y_pred_NB , y_test))

              precision    recall  f1-score   support

           0       0.80      0.83      0.82       107
           1       0.73      0.69      0.71        71

    accuracy                           0.78       178
   macro avg       0.77      0.76      0.76       178
weighted avg       0.77      0.78      0.77       178

In [ ]:
print(f'Naive Bayes accuracy: {accuracy_score(y_pred_knn , y_test)}')

Naive Bayes accuracy: 0.8089887640449438

**Decision Tree**

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
DT_model = DecisionTreeClassifier(random_state = 42)

In [ ]:
DT_model.fit(x_train_scaled , y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
y_pred_DT = DT_model.predict(x_test_scaled)

In [ ]:
confusion_matrix(y_pred_DT , y_test)

array([[95, 21],
       [16, 46]])

In [ ]:
print(classification_report(y_pred_DT , y_test))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84       116
           1       0.69      0.74      0.71        62

    accuracy                           0.79       178
   macro avg       0.77      0.78      0.78       178
weighted avg       0.80      0.79      0.79       178

In [ ]:
print(f'Decision Tree classifier: {accuracy_score(y_pred_DT , y_test)}')

Decision Tree classifier: 0.7921348314606742

**Support Vector Machine**

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc_model = SVC(kernel = 'rbf')

In [ ]:
svc_model.fit(x_train_scaled , y_train)

SVC()

In [ ]:
y_pred_svc = svc_model.predict(x_test_scaled)

In [ ]:
confusion_matrix(y_pred_svc , y_test)

array([[97, 18],
       [14, 49]])

In [ ]:
print(classification_report(y_pred_svc , y_test))

              precision    recall  f1-score   support

           0       0.87      0.84      0.86       115
           1       0.73      0.78      0.75        63

    accuracy                           0.82       178
   macro avg       0.80      0.81      0.81       178
weighted avg       0.82      0.82      0.82       178

In [ ]:
print(f'SVM accuracy: {accuracy_score(y_pred_svc , y_test)}')

SVM accuracy: 0.8202247191011236